<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>category-analysis</artifactId>
        <groupId>org.dromara</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>category-analysis-diagnosis</module>
        <module>category-analysis-demo</module>
        <module>category-analysis-generator</module>
        <module>category-analysis-job</module>
        <module>category-analysis-system</module>
        <module>category-analysis-workflow</module>
    </modules>

    <artifactId>category-analysis-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        category-analysis-modules 业务模块
    </description>

</project>
